apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-stack
  labels:
    app: lamp-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-stack
  template:
    metadata:
      labels:
        app: lamp-stack
    spec:
      containers:
      - name: lamp
        image: your-registry/lamp-stack:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  selector:
    app: lamp-stack
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lamp-route
spec:
  to:
    kind: Service
    name: lamp-service
  port:
    targetPort: 8080