apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-stack
  labels:
    app: lamp-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-stack
  template:
    metadata:
      labels:
        app: lamp-stack
    spec:
      securityContext:
        runAsUser: 0  # Run as root to allow user modification
      containers:
      - name: lamp
        image: your-registry/lamp-stack:latest
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 0  # Run as root in container
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5